services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=simple_blog_api
    api:
        build: ./
        image: docker.io/saswati257/simple-blog-api    
        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api
            - PORT=3000
        ports:
            - "8081:3000"
